# Generated by Django 4.0.6 on 2022-07-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subdiv', models.CharField(max_length=20, verbose_name='Имя подразделения')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='executor.executor', verbose_name='Менеджер проекта')),
            ],
        ),
        migrations.CreateModel(
            name='GroupExecut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('Back', 'BackEnd'), ('Front', 'FrontEnd'), ('Fillst', 'FullStak')], max_length=6, verbose_name='Направление')),
                ('name_group', models.CharField(max_length=20, verbose_name='Имя группы')),
                ('execut', models.ManyToManyField(to='executor.executor', verbose_name='Участники группы')),
                ('sibdivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivision.subdivision', verbose_name='Подразделение')),
            ],
        ),
    ]
