# Generated by Django 4.0.6 on 2022-07-31 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название проекта')),
                ('body', models.TextField(max_length=150, verbose_name='Краткое описание')),
                ('file', models.FileField(upload_to='file_save', verbose_name='Файл с проектом')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.executor', verbose_name='Исполнитель')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название задачи')),
                ('body', models.TextField(max_length=150, verbose_name='Краткое описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='file_save', verbose_name='Файл с задачей')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.executor', verbose_name='Исполнитель')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project', verbose_name='Проект')),
            ],
        ),
    ]
